services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: the_application_name
      POSTGRES_PASSWORD: the_application_name
      POSTGRES_DB: the_application_name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "6664:8080"
    depends_on:
      - db

  app:
    image: the_application_name:local
    profiles:
      - full
    environment:
      POSTGRES_URL: postgresql://the_application_name:the_application_name@db:5432/the_application_name
    ports:
      - "6663:7001"
    depends_on:
      - db

volumes:
  postgres_data:
